name: The Wayman Agency
favicon: null
layout_spectrum: 0.9805513932369649
typography_spectrum: 0.46104
title: The Wayman Agency
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#d7e9f5'
    - '#101c4c'
    - '#216ac9'
    - '#c4b493'
    - '#709426'
  brandStrength: 0.5
  lightness: 0.75
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
